# Generated by Django 3.1.4 on 2021-01-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
